/**
 * Build the standalone artifacts.
 *
 *   node --experimental-strip-types standalone/scripts/build.ts
 *
 * Produces, in standalone/dist/:
 *   jsperf.html        the full app, self-contained, localStorage-backed
 *   jsperf-kiosk.html  the runner-only kiosk template (no case baked in)
 *   jsperf-pack.mjs    the CLI that bakes a case into a copy of that template
 *
 * plus dist-publish/ (buildhost's <binary>_<os>_<arch> naming) and dist-site/
 * (an index.html tree for buildhost static-site hosting).
 *
 * This script is TypeScript like everything else here, run through Node's type
 * stripping. It cannot type-check itself before it starts - it is what fetches
 * the compiler - so the first thing it does after resolving ts0 is run the
 * project's type-check gate, which covers scripts/ along with src/: a type error
 * in the harness fails the build before any artifact is written.
 *
 * ts0 is fetched as the prebuilt platform-neutral ts0.cjs from buildhost and
 * cached under standalone/.cache; set TS0 to use a local build instead
 * (e.g. TS0=../ts0/dist/ts0).
 *
 * The build is four ts0 invocations with two codegen steps between them, because
 * two artifacts need another artifact as a string:
 *   1. sandbox driver (.ts -> iife JS), concatenated after app/lib/benchmark.mjs
 *      -> src/generated/sandbox-bundle.ts, embedded by both HTML builds and
 *      handed to a sandboxed iframe at run time.
 *   2. kiosk HTML -> pack/src/generated/kiosk-template.ts, embedded in the CLI
 *      so packaging needs no checkout.
 */

import { spawnSync } from 'node:child_process'
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const standaloneDir = resolve(scriptDir, '..')
const repoDir = resolve(standaloneDir, '..')

/** Benchmark.js, vendored once for the whole repository. */
const BENCHMARK_SOURCE = join(repoDir, 'app', 'lib', 'benchmark.mjs')

/**
 * Benchmark.js 2.x is not standalone: runInContext() returns a stub with nothing
 * but runInContext on it unless it can acquire lodash (through a module system,
 * or as the global `_`). The Next.js app gets it from webpack; the sandbox script
 * has no module system, so lodash goes in front of it as a plain script and the
 * UMD tail assigns the global Benchmark.js then picks up.
 */
const LODASH_SOURCE = join(standaloneDir, 'node_modules', 'lodash', 'lodash.min.js')

const TS0_URL = process.env.TS0_URL ?? 'https://dl.pazer.build/ts0?os=linux&arch=amd64'
const TS0_CACHE = join(standaloneDir, '.cache', 'ts0.cjs')

const BUILD_STAMP = (process.env.GITHUB_SHA ?? '').slice(0, 12) || 'dev'

function log(message: string): void {
  process.stderr.write(`[build] ${message}\n`)
}

function fail(message: string): never {
  process.stderr.write(`[build] error: ${message}\n`)
  process.exit(1)
}

async function resolveTs0(): Promise<string[]> {
  const override = process.env.TS0
  if (override) {
    const path = resolve(process.cwd(), override)
    if (!existsSync(path)) fail(`TS0=${override} does not exist`)
    log(`using ts0 from TS0=${override}`)
    return [path]
  }

  if (!existsSync(TS0_CACHE)) {
    log(`downloading prebuilt ts0 from ${TS0_URL}`)
    mkdirSync(dirname(TS0_CACHE), { recursive: true })
    const response = await fetch(TS0_URL)
    if (!response.ok) {
      fail(`could not download ts0 (HTTP ${response.status}) from ${TS0_URL}`)
    }
    // Write then rename: an interrupted download must not leave a half file
    // that later runs would happily execute.
    writeFileSync(`${TS0_CACHE}.part`, Buffer.from(await response.arrayBuffer()))
    renameSync(`${TS0_CACHE}.part`, TS0_CACHE)
    log(`cached ts0 at ${TS0_CACHE} (${Math.round(statSync(TS0_CACHE).size / 1024 / 1024)} MiB)`)
  }
  return [TS0_CACHE]
}

function runTs0(ts0: string[], args: string[], cwd: string, label: string): void {
  log(`${label}: ts0 ${args.join(' ')}`)
  const result = spawnSync(process.execPath, [...ts0, ...args], { cwd, stdio: 'inherit' })
  if (result.error) fail(`${label}: ${result.error.message}`)
  if (result.status !== 0) fail(`${label}: ts0 exited ${String(result.status)}`)
}

function writeGenerated(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true })
  const header = [
    '// Generated by standalone/scripts/build.ts. Do not edit and do not commit:',
    '// it is a build input, rebuilt from source on every build.',
    ''
  ].join('\n')
  writeFileSync(path, `${header}${body}`)
}

function assertNoScriptTerminator(js: string, what: string): void {
  if (/<\/script/i.test(js)) {
    fail(`${what} contains "</script", which cannot be inlined into a script element`)
  }
}

const generated = {
  sandbox: join(standaloneDir, 'src', 'generated', 'sandbox-bundle.ts'),
  kiosk: join(standaloneDir, 'pack', 'src', 'generated', 'kiosk-template.ts')
}

/**
 * The type-check gate covers every source in the project, so the generated
 * modules have to exist before the first build that imports them. Stubs make a
 * fresh clone build; each is overwritten with the real thing in step order.
 */
function writeStubs(): void {
  if (!existsSync(generated.sandbox)) {
    writeGenerated(generated.sandbox, 'export const SANDBOX_BUNDLE: string = ""\n')
  }
  if (!existsSync(generated.kiosk)) {
    writeGenerated(
      generated.kiosk,
      'export const KIOSK_TEMPLATE: string = ""\nexport const KIOSK_TEMPLATE_VERSION: string = "stub"\n'
    )
  }
}

function copyInto(dir: string, files: [string, string][]): void {
  mkdirSync(dir, { recursive: true })
  for (const [from, to] of files) {
    copyFileSync(from, join(dir, to))
  }
}

async function main(): Promise<void> {
  const ts0 = await resolveTs0()

  if (!existsSync(BENCHMARK_SOURCE)) {
    fail(`Benchmark.js not found at ${BENCHMARK_SOURCE}`)
  }
  if (!existsSync(LODASH_SOURCE)) {
    fail(`lodash not found at ${LODASH_SOURCE}: run "npm ci" in standalone/ first`)
  }

  writeStubs()

  // 1. The in-iframe driver. This first build is also what type-checks the whole
  //    project, this script included: ts0's gate covers every .ts under
  //    standalone/ regardless of which entry is being built.
  runTs0(ts0, ['build', '--config', 'ts0.sandbox.json'], standaloneDir, 'sandbox driver')
  const driver = readFileSync(join(standaloneDir, 'build', 'sandbox-driver.js'), 'utf-8')

  // 2. Benchmark.js + driver = the sandbox document's whole script. Concatenated
  //    rather than imported: benchmark.mjs is a UMD bundle that assigns
  //    window.Benchmark, and reusing it verbatim keeps one copy of the library in
  //    the repository instead of a fork that drifts from the Next.js app's.
  const benchmark = readFileSync(BENCHMARK_SOURCE, 'utf-8')
  const lodash = readFileSync(LODASH_SOURCE, 'utf-8')
  const sandboxBundle = [
    '/* lodash (MIT) + Benchmark.js (MIT, app/lib/benchmark.mjs) + the jsPerf sandbox driver. */',
    lodash,
    ';',
    benchmark,
    ';',
    // Benchmark.js captured its own reference to lodash when it loaded, so the
    // global can go: the benchmarked code should see the globals a plain page
    // has, not the runner's dependencies.
    'try { delete window._ } catch (e) { void e }',
    ';',
    driver
  ].join('\n')
  assertNoScriptTerminator(sandboxBundle, 'the sandbox bundle')
  writeGenerated(generated.sandbox, `export const SANDBOX_BUNDLE: string = ${JSON.stringify(sandboxBundle)}\n`)
  log(`sandbox bundle: ${Math.round(sandboxBundle.length / 1024)} KiB`)

  // 3. The kiosk page (runner only), which is also the template the CLI fills in.
  runTs0(ts0, ['build', '--config', 'ts0.kiosk.json'], standaloneDir, 'kiosk')
  const kioskPath = join(standaloneDir, 'dist', 'jsperf-kiosk.html')
  const kiosk = readFileSync(kioskPath, 'utf-8')
  writeGenerated(
    generated.kiosk,
    [
      `export const KIOSK_TEMPLATE: string = ${JSON.stringify(kiosk)}`,
      `export const KIOSK_TEMPLATE_VERSION: string = ${JSON.stringify(BUILD_STAMP)}`,
      ''
    ].join('\n')
  )

  // 4. The app page (editor + localStorage + runner).
  runTs0(ts0, ['build', '--config', 'ts0.json'], standaloneDir, 'app')

  // 5. The packaging CLI, with the kiosk template from step 3 inside it.
  runTs0(ts0, ['build'], join(standaloneDir, 'pack'), 'pack CLI')
  const packPath = join(standaloneDir, 'dist', 'jsperf-pack.mjs')
  chmodSync(packPath, 0o755)

  // Publish layouts. buildhost's publish action maps <binary>_<os>_<arch> to a
  // project, and cosmo/any is its multi-platform alias: one stored body served
  // for every os/arch pair, which is what a platform-neutral HTML file or Node
  // script wants. Names are the contract with .github/workflows/ci.yml.
  const appPath = join(standaloneDir, 'dist', 'jsperf.html')
  copyInto(join(standaloneDir, 'dist-publish'), [
    [appPath, 'jsperf.app_cosmo_any'],
    [kioskPath, 'jsperf.app-kiosk_cosmo_any'],
    [packPath, 'jsperf.app-pack_cosmo_any']
  ])

  // Static-site layout: the app is the index, so the deployed URL opens straight
  // into a working jsPerf.
  copyInto(join(standaloneDir, 'dist-site'), [
    [appPath, 'index.html'],
    [kioskPath, 'kiosk.html'],
    [packPath, 'jsperf-pack.mjs']
  ])

  for (const [label, path] of [
    ['app  ', appPath],
    ['kiosk', kioskPath],
    ['pack ', packPath]
  ]) {
    log(`${label} ${path} (${Math.round(statSync(path).size / 1024)} KiB)`)
  }
  log(`done (stamp ${BUILD_STAMP})`)
}

await main()
